### ISSUE TITLE
enable discussions for dev-sec org

### ISSUE THREAD

**Issue by deric4** [dev-sec/.github#19]
### Description

When reading through issues/PRs, I sometimes find there are references/cross links to provide   to other issues/PRs in dev-sec projects to provide context/reason/implementation details i.e.:

- [ ] https://github.com/dev-sec/puppet-os-hardening/issues/275
- [ ] https://github.com/dev-sec/linux-baseline/issues/140
- [ ] https://github.com/dev-sec/ssh-baseline/issues/148
- [ ] https://github.com/dev-sec/linux-baseline/issues/171

Other times I may notice a difference in how the same task is implemented between Project-A and Project-B and curious about pros/cons and would like to ask a question. Maintainers of Project-A might not be the same maintainers of Project-B, which leaves me unsure of what the most "polite" thing to do is. Opening issues in both projects with same question to increase visibility feels a bit "rude" and noisy...

Enabling discussion for the Org would also allow for migrating any existing Team Discussions which were deprecated May 8, 2023

https://github.blog/changelog/2023-02-08-sunset-notice-team-discussions/

### Solution

Enable organization discussions and encourage users to label questions with related projects/standards/etc

examples labels:

- `ansible-collection-hardening`
- `puppet-os-hardening`
- `CIS`
- `networking`
- `logging`

### Alternatives

keep status quo

### Additional information

...

**Comment by rndmh3ro** [comment]
Good idea! Done -> https://github.com/dev-sec/.github/discussions/21
